<?php

defined( 'ABSPATH' ) || exit;

/**
 * Canonical, bounded cache variation context.
 *
 * The class deliberately has no WordPress dependencies. The same code is
 * therefore safe to use while the advanced-cache drop-in is executing and
 * after WordPress has loaded all active integrations.
 *
 * @package Breeze
 */
final class Breeze_Cache_Variation_Context {

	/** @var int Maximum length of one configured or request value. */
	const MAX_VALUE_LENGTH = 32;

	/** @var int Maximum number of variation dimensions in trusted metadata. */
	const MAX_DIMENSIONS = 16;

	/** @var int Maximum number of values in one trusted dimension. */
	const MAX_VALUES_PER_DIMENSION = 128;

	/** @var string Fixed suffix for invalid asset contexts. */
	const INVALID_ASSET_SUFFIX = '-invalid';

	/** @var array<string,array<int,string>> */
	private $allowlist;

	/** @var array<string,string> */
	private $values;

	/** @var bool */
	private $valid;

	/** @var string */
	private $key;

	/**
	 * @param array<string,array<int,string>> $allowlist Normalized allowlist.
	 * @param array<string,string> $values Normalized request values.
	 * @param bool $valid Whether request values are valid.
	 */
	private function __construct( array $allowlist, array $values, $valid ) {
		$this->allowlist = $allowlist;
		$this->values    = $values;
		$this->valid     = (bool) $valid;
		$this->key       = $this->build_key( $values );
	}

	/**
	 * Build a context from trusted configured values and request values.
	 *
	 * Unknown dimensions are ignored so an inactive integration cannot affect
	 * the cache. A missing value means the integration's default page context;
	 * an explicitly supplied empty, malformed, or unknown value is invalid.
	 *
	 * @param array<string,array<int,string>> $allowlist Trusted configured values.
	 * @param array<string,mixed> $request_values Client/request values.
	 *
	 * @return self
	 */
	public static function from_allowlist( array $allowlist, array $request_values = array() ) {
		$normalized_allowlist = self::serialize_allowlist( $allowlist );
		$values               = array();
		$valid                = true;

		foreach ( $normalized_allowlist as $dimension => $configured_values ) {
			if ( ! array_key_exists( $dimension, $request_values ) ) {
				continue;
			}

			$value = self::normalize_value( $request_values[ $dimension ] );
			if ( null === $value || ! in_array( $value, $configured_values, true ) ) {
				$valid = false;
				continue;
			}

			$values[ $dimension ] = $value;
		}

		ksort( $values, SORT_STRING );

		return new self( $normalized_allowlist, $values, $valid );
	}

	/**
	 * Build a context from configuration generated by Breeze.
	 *
	 * Only the serialized allowlist is trusted from the generated file. Request
	 * values are always validated again by from_allowlist().
	 *
	 * @param array<string,mixed> $config Breeze configuration.
	 * @param array<string,mixed> $request_values Client/request values.
	 *
	 * @return self
	 */
	public static function from_config( array $config, array $request_values = array() ) {
		$variation_config = self::get_variation_config( $config );
		$allowlist        = isset( $variation_config['cache_variation_allowlist'] ) && is_array( $variation_config['cache_variation_allowlist'] )
			? $variation_config['cache_variation_allowlist']
			: array();

		return self::from_allowlist( $allowlist, $request_values );
	}

	/**
	 * Select variation metadata for the current multisite blog.
	 *
	 * Root configuration is shared by inherited subsites, so its variation
	 * metadata is stored per blog. Custom site configuration continues to use
	 * the top-level metadata.
	 *
	 * @param array<string,mixed> $config Breeze configuration.
	 *
	 * @return array<string,mixed>
	 */
	public static function get_variation_config( array $config ) {
		if ( ! isset( $config['blog_id'], $config['cache_variation_by_blog'] ) || ! is_array( $config['cache_variation_by_blog'] ) ) {
			return $config;
		}

		$blog_id = (int) $config['blog_id'];
		if ( $blog_id <= 0 || ! isset( $config['cache_variation_by_blog'][ $blog_id ] ) || ! is_array( $config['cache_variation_by_blog'][ $blog_id ] ) ) {
			return $config;
		}

		return array_merge( $config, $config['cache_variation_by_blog'][ $blog_id ] );
	}

	/**
	 * Normalize and bound trusted metadata before it is written to config.
	 *
	 * Invalid configured entries are omitted. This keeps a damaged integration
	 * setting from making early-cache execution fatal or unsafe.
	 *
	 * @param array<string,mixed> $allowlist
	 *
	 * @return array<string,array<int,string>>
	 */
	public static function serialize_allowlist( array $allowlist ) {
		$normalized = array();
		$dimensions = array_keys( $allowlist );
		sort( $dimensions, SORT_STRING );

		foreach ( $dimensions as $raw_dimension ) {
			if ( count( $normalized ) >= self::MAX_DIMENSIONS || ! is_string( $raw_dimension ) ) {
				continue;
			}

			$dimension = self::normalize_dimension( $raw_dimension );
			if ( null === $dimension || ! is_array( $allowlist[ $raw_dimension ] ) ) {
				continue;
			}

			$values = array();
			foreach ( $allowlist[ $raw_dimension ] as $value ) {
				if ( count( $values ) >= self::MAX_VALUES_PER_DIMENSION ) {
					break;
				}

				$value = self::normalize_value( $value );
				if ( null !== $value ) {
					$values[ $value ] = $value;
				}
			}

			if ( empty( $values ) ) {
				continue;
			}

			$values = array_values( $values );
			sort( $values, SORT_STRING );
			$normalized[ $dimension ] = $values;
		}

		ksort( $normalized, SORT_STRING );

		return $normalized;
	}

	/**
	 * Merge trusted integration metadata without allowing one integration to
	 * replace another integration's values.
	 *
	 * @param array<string,array<int,string>> $allowlist Existing metadata.
	 * @param array<string,array<int,string>> $addition Additional metadata.
	 *
	 * @return array<string,array<int,string>>
	 */
	public static function merge_allowlist( array $allowlist, array $addition ) {
		foreach ( $addition as $dimension => $values ) {
			if ( ! is_array( $values ) ) {
				continue;
			}

			if ( ! isset( $allowlist[ $dimension ] ) || ! is_array( $allowlist[ $dimension ] ) ) {
				$allowlist[ $dimension ] = array();
			}

			$allowlist[ $dimension ] = array_merge( $allowlist[ $dimension ], $values );
		}

		return $allowlist;
	}

	/**
	 * Whether all supplied values were valid configured values.
	 *
	 * @return bool
	 */
	public function is_valid() {
		return $this->valid;
	}

	/**
	 * Invalid contexts must not enter shared full-page cache.
	 *
	 * @return bool
	 */
	public function is_page_cacheable() {
		return $this->valid;
	}

	/**
	 * Invalid contexts must not create minified asset files.
	 *
	 * @return bool
	 */
	public function can_create_asset_cache() {
		return $this->valid;
	}

	/**
	 * Return normalized values that actually participate in this context.
	 *
	 * @return array<string,string>
	 */
	public function get_values() {
		return $this->values;
	}

	/**
	 * Return the stable key for page-cache keys and ETags.
	 *
	 * @return string Empty for the default context.
	 */
	public function get_key() {
		return $this->key;
	}

	/**
	 * Return a bounded, filesystem-safe asset suffix.
	 *
	 * @return string
	 */
	public function get_asset_suffix() {
		if ( ! $this->valid ) {
			return self::INVALID_ASSET_SUFFIX;
		}

		if ( '' === $this->key ) {
			return '';
		}

		return '-cv' . substr( $this->key, 0, 16 );
	}

	/**
	 * Return the normalized allowlist for diagnostics and generated metadata.
	 *
	 * @return array<string,array<int,string>>
	 */
	public function get_allowlist() {
		return $this->allowlist;
	}

	/**
	 * Append the context to a page cache key without exposing raw values.
	 *
	 * @param string $cache_key Existing URL cache key.
	 *
	 * @return string
	 */
	public function append_to_cache_key( $cache_key ) {
		if ( ! $this->valid || '' === $this->key ) {
			return (string) $cache_key;
		}

		$separator = false !== strpos( (string) $cache_key, '?' ) ? '&' : '?';

		return (string) $cache_key . $separator . 'breeze_variation=' . $this->key;
	}

	/**
	 * Build a deterministic hash from normalized dimensions.
	 *
	 * @param array<string,string> $values
	 *
	 * @return string
	 */
	private function build_key( array $values ) {
		if ( empty( $values ) ) {
			return '';
		}

		$json = json_encode( $values, JSON_UNESCAPED_SLASHES );
		if ( false === $json ) {
			return '';
		}

		return hash( 'sha256', 'breeze-cache-variation-v1|' . $json );
	}

	/**
	 * Normalize one request/configured value after raw type and syntax checks.
	 *
	 * @param mixed $value
	 *
	 * @return string|null
	 */
	private static function normalize_value( $value ) {
		if ( ! is_string( $value ) || '' === $value || strlen( $value ) > self::MAX_VALUE_LENGTH ) {
			return null;
		}

		if ( false !== strpos( $value, '..' ) || false !== strpos( $value, '\\' ) || preg_match( '/%(?:2e|2f|5c)/i', $value ) ) {
			return null;
		}

		if ( 1 !== preg_match( '/\A[A-Za-z0-9][A-Za-z0-9_-]{0,31}\z/D', $value ) ) {
			return null;
		}

		return strtolower( $value );
	}

	/**
	 * Normalize a dimension name used in trusted metadata.
	 *
	 * @param mixed $dimension
	 *
	 * @return string|null
	 */
	private static function normalize_dimension( $dimension ) {
		if ( ! is_string( $dimension ) || strlen( $dimension ) > self::MAX_VALUE_LENGTH ) {
			return null;
		}

		if ( 1 !== preg_match( '/\A[a-z][a-z0-9_-]{0,31}\z/D', $dimension ) ) {
			return null;
		}

		return strtolower( $dimension );
	}
}
